CREATE SCHEMA `letseat` ;

CREATE TABLE `letseat`.`restaurants` (
  `restID` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `CuisineType` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`restID`),
  UNIQUE INDEX `restID_UNIQUE` (`restID` ASC) VISIBLE);
  
  CREATE TABLE `letseat`.`favorites` (
  `restID` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `CuisineType` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`restID`),
  UNIQUE INDEX `restID_UNIQUE` (`restID` ASC) VISIBLE);